apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
spec:
  selector:
    app: mon-app
  ports:
    - protocol: TCP
      port: 80        # port du service dans le cluster
      targetPort: 80  # port du container nginx
  type: NodePort
